In [3]:
#when ever we access the size of the data frame it is written in tuple
#one single columed or one  rows in a df is called series in python
#to install library.....(!pip install package_name) 
#pamdas are build on top of numpy
!pip install sklearn


!pip install nltk

In [5]:
!pip install collections

  ERROR: Could not find a version that satisfies the requirement collections (from versions: none)
ERROR: No matching distribution found for collections


In [6]:
!pip install scipy

In [2]:
import pandas as pd #mostly used to modify the df
import numpy as np
import sklearn

In [22]:
#definind a array in 2 dimentions(rows and colums)
array_2d=np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13]])
array_2d

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [23]:
array_2d=np.array([[1,2,3,4],[6,7,8,9],[10,11,12,'abc']])  #output is all str if one input value is str
array_2d

array([['1', '2', '3', '4'],
       ['6', '7', '8', '9'],
       ['10', '11', '12', 'abc']], dtype='<U11')

In [24]:
array_2d=np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13.34]])  # outputs are floates if one input value is float
array_2d

array([[ 1.  ,  2.  ,  3.  ,  4.  ],
       [ 6.  ,  7.  ,  8.  ,  9.  ],
       [10.  , 11.  , 12.  , 13.34]])

In [25]:
array_2d=np.array([[1,2,3,4],[6,7.8,8,9],[10,11,12,'csk']])  # outputs are str a if one input value is float and str
array_2d  
#all the elements should have same lengh to build a df

array([['1', '2', '3', '4'],
       ['6', '7.8', '8', '9'],
       ['10', '11', '12', 'csk']], dtype='<U32')

In [26]:
array_2d.shape  #to know the shape of the array

(3, 4)

In [27]:
type(array_2d)

numpy.ndarray

In [30]:
arr_1d=np.array([[1,2,3,4]])  #defining a 2D array with one row and 4 colums
arr_1d.shape


(1, 4)

In [31]:
type(arr_1d)  #1D array means one vector

numpy.ndarray

In [32]:
arr_1d=np.array([1,2,3,4])   #defining a 1D array with 4 rows and 1 column
arr_1d.shape

(4,)

In [3]:
a1=np.array([['shekar',24,'m',5.5,'telangana'],['priya',25,'f',5,'ap'],['rani',30,'f',5.8,'orisa'],['sushanth',28,'m',5.9,'tamil'],['dk',33,'m',6,'hyd']])
a1

array([['shekar', '24', 'm', '5.5', 'telangana'],
       ['priya', '25', 'f', '5', 'ap'],
       ['rani', '30', 'f', '5.8', 'orisa'],
       ['sushanth', '28', 'm', '5.9', 'tamil'],
       ['dk', '33', 'm', '6', 'hyd']], dtype='<U9')

In [37]:
a1[2,0]  # to access single element in array,  a1[row index, column index]

'rani'

In [38]:
a1[2,] #accessing

array(['rani', '30', 'f', '5.8', 'orisa'], dtype='<U9')

In [39]:
a1[2,].shape  # output is a vector

(5,)

In [40]:
a1[,2]

SyntaxError: invalid syntax (<ipython-input-40-278c1c2dc12f>, line 1)

In [41]:
a1[:,2]  #

array(['m', 'f', 'f', 'm', 'm'], dtype='<U9')

In [43]:
a1[2,:] #to get all elements of 3 row

array(['rani', '30', 'f', '5.8', 'orisa'], dtype='<U9')

In [5]:
print(a1)   #multiple accessing
a1[[1,2,3],[2,3,4]]
print('=====')
print(a1)
a1[(1,2),(2,3)]

[['shekar' '24' 'm' '5.5' 'telangana']
 ['priya' '25' 'f' '5' 'ap']
 ['rani' '30' 'f' '5.8' 'orisa']
 ['sushanth' '28' 'm' '5.9' 'tamil']
 ['dk' '33' 'm' '6' 'hyd']]
=====
[['shekar' '24' 'm' '5.5' 'telangana']
 ['priya' '25' 'f' '5' 'ap']
 ['rani' '30' 'f' '5.8' 'orisa']
 ['sushanth' '28' 'm' '5.9' 'tamil']
 ['dk' '33' 'm' '6' 'hyd']]


array(['f', '5.8'], dtype='<U9')

In [53]:
a1[2,0]='devi'  #assing new values to the data
a1

array([['shekar', '24', 'm', '5.5', 'telangana'],
       ['priya', '25', 'f', '5', 'ap'],
       ['devi', '30', 'f', '5.8', 'orisa'],
       ['sushanth', '28', 'm', '5.9', 'tamil'],
       ['dk', '33', 'm', '6', 'hyd']], dtype='<U9')

In [54]:
a1>0

TypeError: '>' not supported between instances of 'numpy.ndarray' and 'int'

In [40]:
a2=np.array([[1,2,3],[2,3,4],[4,5,6]])  #compares every element > 0 or not
print(a2)
a2>0

[[1 2 3]
 [2 3 4]
 [4 5 6]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [57]:
a2+1  # it adds 1 to every element

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [59]:
a3=np.array([['ac','xz'],['ds','cd'],['fr','ef']]) 
print(a3)
a3+'dk'

[['ac' 'xz']
 ['ds' 'cd']
 ['fr' 'ef']]


TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U2') dtype('<U2') dtype('<U2')

In [61]:
#to have the sum of all elments
print(a2)
np.sum(a2)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


30

In [64]:
print(a2)
p=np.sum(a2[0,])
print(p)
np.sum(a2[:,2])

[[1 2 3]
 [2 3 4]
 [4 5 6]]
6


13

In [65]:
#axis=0 for column axis=1 for row  only in sum function
#sum of each columns
print(a2)
np.sum(a2,axis=0)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


array([ 7, 10, 13])

In [66]:
#sum of each row
print(a2)
np.sum(a2,axis=1)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


array([ 6,  9, 15])

In [5]:
print(a1)  #to delet the columns in a df
np.delete(a1,[0,2,4],1)  #here 1 is axis=1 for deleting columns, to delet single column
#except for sum (axis=1 for row), rest all functions axis=1 for columns


[['shekar' '24' 'm' '5.5' 'telangana']
 ['priya' '25' 'f' '5' 'ap']
 ['rani' '30' 'f' '5.8' 'orisa']
 ['sushanth' '28' 'm' '5.9' 'tamil']
 ['dk' '33' 'm' '6' 'hyd']]


array([['24', '5.5'],
       ['25', '5'],
       ['30', '5.8'],
       ['28', '5.9'],
       ['33', '6']], dtype='<U9')

In [15]:
np.arange(0,10)#declaring a range in numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:

list(np.arange(0,10))  #list of range values

[0 1 2 3 4 5 6 7 8 9]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
type(range(0,10))

range

In [13]:
type(np.arange(0,10))

numpy.ndarray

In [14]:
np.arange(0,10,2)  # here 2 is the step value, output values will be in steps of 2

array([0, 2, 4, 6, 8])

In [16]:
?np.arange

In [21]:
np.linspace(2,10,15)  #in a range of 2 to 10....vector of 15 elements is created

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [25]:
?np.linspace

In [28]:
#defining random numbers 
np.random.randint(1,15,10)

array([10, 14,  9,  9, 10,  2, 10,  4,  9, 11])

In [29]:
?np.random.randint

In [32]:
np.random.randint(1,15,(2,3)) #to define array of 2*3 with random elements

array([[12,  6,  7],
       [12, 12, 14]])

In [35]:
?np.random.random

In [36]:
np.random.random(10) #this function works between 0 and 1, generate random floats

array([0.94791013, 0.8317736 , 0.3785562 , 0.99155701, 0.42092066,
       0.4599096 , 0.4984315 , 0.44230266, 0.16518481, 0.25626331])

In [43]:
?np.random.choice

In [45]:
k=[1,2,3,4]  #random values fron k are created
np.random.choice(k,10,replace=True)

array([4, 4, 4, 4, 4, 3, 4, 4, 3, 3])

In [46]:
k=[1,2,3,4]
np.random.choice(k,10,replace=False)  #bcoz k doent have 10 values and sampling without replacement 

ValueError: Cannot take a larger sample than population when 'replace=False'

In [49]:
#sorting- is done for only for 1D array but not for multiple dimensions
h=np.random.randint(1,50,100)
print(h)
np.sort(h)

[18 16  3 21 39 15 21 10  3 23 36 29 11 46 32 33 10 15 21  5  9  3 11 33
  9 30  9 48 28 16  8 23 41 30 32 44 29 11 27 48 46  4  4 40 19 14 11 42
 44 41  3 28 49 11 27 39 26 28  1 48 48 47  8 34 21  1 40 45 46 20  7 34
 41 25 41  7 46 28 25 37 16 49 46 11 19 41 10 19 46 35 28 11 38 46 40 44
  2 17 20 30]


array([ 1,  1,  2,  3,  3,  3,  3,  4,  4,  5,  7,  7,  8,  8,  9,  9,  9,
       10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 14, 15, 15, 16, 16, 16, 17,
       18, 19, 19, 19, 20, 20, 21, 21, 21, 21, 23, 23, 25, 25, 26, 27, 27,
       28, 28, 28, 28, 28, 29, 29, 30, 30, 30, 32, 32, 33, 33, 34, 34, 35,
       36, 37, 38, 39, 39, 40, 40, 40, 41, 41, 41, 41, 41, 42, 44, 44, 44,
       45, 46, 46, 46, 46, 46, 46, 46, 47, 48, 48, 48, 48, 49, 49])

In [50]:
?np.sort

In [63]:
#reversing a sort by converting to list  to obtain decending order
e=list(np.sort(h))
e.reverse()
np.array(e)
#print('-------')  OR below method

array([49, 49, 48, 48, 48, 48, 47, 46, 46, 46, 46, 46, 46, 46, 45, 44, 44,
       44, 42, 41, 41, 41, 41, 41, 40, 40, 40, 39, 39, 38, 37, 36, 35, 34,
       34, 33, 33, 32, 32, 30, 30, 30, 29, 29, 28, 28, 28, 28, 28, 27, 27,
       26, 25, 25, 23, 23, 21, 21, 21, 21, 20, 20, 19, 19, 19, 18, 17, 16,
       16, 16, 15, 15, 14, 11, 11, 11, 11, 11, 11, 11, 10, 10, 10,  9,  9,
        9,  8,  8,  7,  7,  5,  4,  4,  3,  3,  3,  3,  2,  1,  1])

In [69]:
e=list(np.sort(h))
x=e[::-1]
print(x)
np.array(x)

[49, 49, 48, 48, 48, 48, 47, 46, 46, 46, 46, 46, 46, 46, 45, 44, 44, 44, 42, 41, 41, 41, 41, 41, 40, 40, 40, 39, 39, 38, 37, 36, 35, 34, 34, 33, 33, 32, 32, 30, 30, 30, 29, 29, 28, 28, 28, 28, 28, 27, 27, 26, 25, 25, 23, 23, 21, 21, 21, 21, 20, 20, 19, 19, 19, 18, 17, 16, 16, 16, 15, 15, 14, 11, 11, 11, 11, 11, 11, 11, 10, 10, 10, 9, 9, 9, 8, 8, 7, 7, 5, 4, 4, 3, 3, 3, 3, 2, 1, 1]


array([49, 49, 48, 48, 48, 48, 47, 46, 46, 46, 46, 46, 46, 46, 45, 44, 44,
       44, 42, 41, 41, 41, 41, 41, 40, 40, 40, 39, 39, 38, 37, 36, 35, 34,
       34, 33, 33, 32, 32, 30, 30, 30, 29, 29, 28, 28, 28, 28, 28, 27, 27,
       26, 25, 25, 23, 23, 21, 21, 21, 21, 20, 20, 19, 19, 19, 18, 17, 16,
       16, 16, 15, 15, 14, 11, 11, 11, 11, 11, 11, 11, 10, 10, 10,  9,  9,
        9,  8,  8,  7,  7,  5,  4,  4,  3,  3,  3,  3,  2,  1,  1])

In [73]:
#
h=[3,2,9,8,7,1]
print(h)
x=np.sort(h)
print(x)
np.argsort(h) #output wil be index values of the sort elements refering to actual list

[3, 2, 9, 8, 7, 1]
[1 2 3 7 8 9]


array([5, 1, 0, 4, 3, 2], dtype=int64)